Manager:
    LoginScreen:
    MainScreen:

<LoginScreen>:
    name: "login"
    BoxLayout:
        orientation: "vertical"
        padding: 40
        spacing: 20

        Label:
            text: "Cyber Toolkit"
            font_size: 24

        TextInput:
            id: pass_input
            hint_text: "Enter Password"
            password: True

        Button:
            text: "Login"
            on_press: root.check_password()


<MainScreen>:
    name: "main"

    BoxLayout:
        orientation: "vertical"

        TabbedPanel:
            do_default_tab: False

            TabbedPanelItem:
                text: "Network"
                BoxLayout:
                    orientation: "vertical"
                    padding: 10

                    TextInput:
                        id: input1
                        hint_text: "Domain / IP"

                    Button:
                        text: "DNS Lookup"
                        on_press: root.dns_lookup(input1.text)

                    Button:
                        text: "IP Info"
                        on_press: root.ip_info(input1.text)

            TabbedPanelItem:
                text: "Web"
                BoxLayout:
                    orientation: "vertical"
                    padding: 10

                    TextInput:
                        id: input2
                        hint_text: "http://example.com"

                    Button:
                        text: "Get Headers"
                        on_press: root.headers(input2.text)

            TabbedPanelItem:
                text: "Security"
                BoxLayout:
                    orientation: "vertical"
                    padding: 10

                    Button:
                        text: "Generate Password"
                        on_press: root.password()

            TabbedPanelItem:
                text: "Device"
                BoxLayout:
                    orientation: "vertical"
                    padding: 10

                    Button:
                        text: "Device Info"
                        on_press: root.device()

        TextInput:
            size_hint_y: 0.3
            text: root.output
            readonly: True
